version: '3.8'

services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: 'habit-tracker'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - "2345:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  habit-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database

volumes:
  postgres-data:
